In [ ]:
import pandas as pd

file_path1 = "user_study_2a_img.tsv"
file_path2 = "user_study_2b_img.tsv"

# Read the TSV file into a DataFrame
df1 = pd.read_csv(file_path1, sep='\t')
df2 = pd.read_csv(file_path2, sep='\t')

df = pd.concat([df1, df2])
df

,attribute_id,attribute_name,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
0,a1_age_approx,Age Group,2,1,2,1,2,1,3,2,...,1,5,1,3,5,1,1,2,4,2
1,a2_weight_approx,Weight Group,2,1,1,1,1,2,3,3,...,1,5,1,2,5,4,1,1,4,1
2,a3_height_approx,Height Group,2,1,1,1,1,1,3,3,...,1,1,3,2,5,1,1,1,4,1
3,a4_gender,Gender,3,1,2,1,1,1,3,2,...,1,5,1,3,5,1,2,1,4,1
4,a5_eye_color,Eye Color,2,1,1,1,2,2,4,2,...,1,5,5,3,4,1,2,2,5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,a97_online_conversation,Online conversations,2,4,3,3,4,4,2,4,...,4,3,4,3,2,3,4,3,4,5
31,a99_legal_involvement,Legal involvement,3,4,4,4,4,5,3,5,...,2,3,5,4,3,3,3,2,5,5
32,a102_vehicle_ownership,Personal Vehicle Ownership,2,4,4,1,5,5,1,5,...,1,1,2,1,2,3,2,4,1,1
33,a103_license_plate_complete,License Plate (Complete),3,3,3,4,5,1,2,5,...,1,4,1,2,3,1,4,3,5,3
34,a104_license_plate_partial,License Plate (Partial),4,2,3,1,2,1,1,3,...,1,1,1,1,2,1,2,2,2,1

In [ ]:
participant_cols = df.columns[2:]
df['average_score'] = df[participant_cols].mean(axis=1, skipna=True)

# Normalize to [0, 1]
df['normalized_score'] = (df['average_score'] - 1) / 4

# View result
df[['attribute_id', 'attribute_name', 'average_score', 'normalized_score']]

,attribute_id,attribute_name,average_score,normalized_score
0,a1_age_approx,Age Group,2.123153,0.280788
1,a2_weight_approx,Weight Group,1.926109,0.231527
2,a3_height_approx,Height Group,1.807882,0.201971
3,a4_gender,Gender,1.847291,0.211823
4,a5_eye_color,Eye Color,2.438424,0.359606
...,...,...,...,...
30,a97_online_conversation,Online conversations,3.108375,0.527094
31,a99_legal_involvement,Legal involvement,3.817735,0.704434
32,a102_vehicle_ownership,Personal Vehicle Ownership,2.004927,0.251232
33,a103_license_plate_complete,License Plate (Complete),2.458129,0.364532
34,a104_license_plate_partial,License Plate (Partial),1.729064,0.182266

In [ ]:
df["attribute_id"].unique()

array(['a1_age_approx', 'a2_weight_approx', 'a3_height_approx',
       'a4_gender', 'a5_eye_color', 'a6_hair_color', 'a7_fingerprint',
       'a8_signature', 'a9_face_complete', 'a10_face_partial',
       'a11_tattoo', 'a12_semi_nudity', 'a13_full_nudity', 'a16_race',
       'a17_color', 'a18_ethnic_clothing', 'a19_name_full',
       'a20_name_first', 'a21_name_last', 'a23_birth_city',
       'a24_birth_date', 'a25_nationality', 'a26_handwriting',
       'a27_marital_status', 'a29_ausweis', 'a30_credit_card',
       'a31_passport', 'a32_drivers_license', 'a33_student_id',
       'a35_mail', 'a37_receipt', 'a38_ticket', 'a39_disability_physical',
       'a41_injury', 'a43_medicine', 'a46_occupation',
       'a48_occassion_work', 'a49_phone', 'a55_religion',
       'a56_sexual_orientation', 'a57_culture', 'a58_hobbies',
       'a59_sports', 'a60_occassion_personal', 'a61_opinion_general',
       'a62_opinion_political', 'a64_rel_personal', 'a65_rel_social',
       'a66_rel_professional', 'a67_rel_competitors',
       'a68_rel_spectators', 'a69_rel_views', 'a70_education_history',
       'a73_landmark', 'a74_address_current_complete',
       'a75_address_current_partial', 'a78_address_home_complete',
       'a79_address_home_partial', 'a82_date_time', 'a85_username',
       'a90_email', 'a92_email_content', 'a97_online_conversation',
       'a99_legal_involvement', 'a102_vehicle_ownership',
       'a103_license_plate_complete', 'a104_license_plate_partial'],
      dtype=object)

In [ ]:
target_attributes = [
    "a9_face_complete", "a74_address_current_complete", "a78_address_home_complete",
    "a103_license_plate_complete", "a109_person_body", "a13_full_nudity",
    "a21_name_last", "a18_ethnic_clothing", "a24_birth_date",
    "a26_handwriting", "a29_ausweis", "a30_credit_card", "a31_passport",
    "a32_drivers_license", "a33_student_id", "a35_mail", "a37_receipt",
    "a38_ticket", "a39_disability_physical", "a43_medicine", "a49_phone",
    "a70_education_history", "a73_landmark", "a7_fingerprint",
    "a82_date_time", "a85_username", "a8_signature", "a90_email"
]

# Filter the DataFrame
filtered_df = df[df['attribute_id'].isin(target_attributes)]

# Show result
filtered_df[['attribute_id', 'attribute_name', 'normalized_score']]

,attribute_id,attribute_name,normalized_score
6,a7_fingerprint,Fingerprint,0.517242
7,a8_signature,Signature,0.847291
8,a9_face_complete,Face (Complete),0.394089
12,a13_full_nudity,Complete nudity,0.768473
15,a18_ethnic_clothing,Traditional clothing,0.325123
18,a21_name_last,Name (Last),0.822660
20,a24_birth_date,Date of Birth,0.729064
22,a26_handwriting,Handwriting,0.768473
24,a29_ausweis,National Identification,0.871921
25,a30_credit_card,Credit Card,0.866995
26,a31_passport,Passport,0.871921
27,a32_drivers_license,Drivers License,0.886700
28,a33_student_id,Student ID,0.881774
29,a35_mail,Mail,0.645320
30,a37_receipt,Receipts,0.724138
31,a38_ticket,Tickets,0.807882
0,a39_disability_physical,Physical disability,0.487685
2,a43_medicine,Medical History,0.783251
5,a49_phone,Phone no.,0.566503
20,a70_education_history,Education history,0.290641
21,a73_landmark,Landmark,0.172414
22,a74_address_current_complete,Previous/Current Location (Complete),0.551724
24,a78_address_home_complete,Home address (Complete),0.724138
26,a82_date_time,Date/Time of Activity,0.467980
27,a85_username,Username,0.561577
28,a90_email,Email address,0.679803
33,a103_license_plate_complete,License Plate (Complete),0.364532

In [ ]:
# Get original min and max
min_score = filtered_df['normalized_score'].min()
max_score = filtered_df['normalized_score'].max()

# Scale to range [0.1, 1]
filtered_df['scaled_score'] = 0.1 + (filtered_df['normalized_score'] - min_score) / (max_score - min_score) * (1 - 0.1)
filtered_df['scaled_score'] = filtered_df['scaled_score'].round(2)

# View result
filtered_df[['attribute_name', 'normalized_score', 'scaled_score']]

<ipython-input-24-8b44744b41ac>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['scaled_score'] = 0.1 + (filtered_df['normalized_score'] - min_score) / (max_score - min_score) * (1 - 0.1)
<ipython-input-24-8b44744b41ac>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['scaled_score'] = filtered_df['scaled_score'].round(2)

                          attribute_name  normalized_score  scaled_score
6                            Fingerprint          0.517242          0.53
7                              Signature          0.847291          0.95
8                        Face (Complete)          0.394089          0.38
12                       Complete nudity          0.768473          0.85
15                  Traditional clothing          0.325123          0.29
18                           Name (Last)          0.822660          0.92
20                         Date of Birth          0.729064          0.80
22                           Handwriting          0.768473          0.85
24               National Identification          0.871921          0.98
25                           Credit Card          0.866995          0.98
26                              Passport          0.871921          0.98
27                       Drivers License          0.886700          1.00
28                            Student ID          0.881774          0.99
29                                  Mail          0.645320          0.70
30                              Receipts          0.724138          0.80
31                               Tickets          0.807882          0.90
0                    Physical disability          0.487685          0.50
2                        Medical History          0.783251          0.87
5                              Phone no.          0.566503          0.60
20                     Education history          0.290641          0.25
21                              Landmark          0.172414          0.10
22  Previous/Current Location (Complete)          0.551724          0.58
24               Home address (Complete)          0.724138          0.80
26                 Date/Time of Activity          0.467980          0.47
27                              Username          0.561577          0.59
28                         Email address          0.679803          0.74
33              License Plate (Complete)          0.364532          0.34

In [ ]:
attribute_score_dict = dict(zip(filtered_df['attribute_id'], filtered_df['scaled_score']))
print(attribute_score_dict)

{'a7_fingerprint': 0.53, 'a8_signature': 0.95, 'a9_face_complete': 0.38, 'a13_full_nudity': 0.85, 'a18_ethnic_clothing': 0.29, 'a21_name_last': 0.92, 'a24_birth_date': 0.8, 'a26_handwriting': 0.85, 'a29_ausweis': 0.98, 'a30_credit_card': 0.98, 'a31_passport': 0.98, 'a32_drivers_license': 1.0, 'a33_student_id': 0.99, 'a35_mail': 0.7, 'a37_receipt': 0.8, 'a38_ticket': 0.9, 'a39_disability_physical': 0.5, 'a43_medicine': 0.87, 'a49_phone': 0.6, 'a70_education_history': 0.25, 'a73_landmark': 0.1, 'a74_address_current_complete': 0.58, 'a78_address_home_complete': 0.8, 'a82_date_time': 0.47, 'a85_username': 0.59, 'a90_email': 0.74, 'a103_license_plate_complete': 0.34}